### ISSUE TITLE
module-info.class: broken class file?

### ISSUE THREAD

**Issue by dangiankit** [fast-classpath-scanner/fast-classpath-scanner#218]
When using the FCS 4.0.0-beta-9 versions in an Android project, at build time, I see the below line repeated 6 times: 

> Error processing `<project-path>`/libs/fast-classpath-scanner-4.0.0-beta-9.jar:module-info.class: broken class file?

I earlier tried to get it from MavenCentral when it gave me the above error, then, used a Pre-built JAR from Sonatype as per [this Wiki](https://github.com/fast-classpath-scanner/fast-classpath-scanner/wiki#pre-built-jars), yet, it did not resolve the issue. It [seems that this is an issue](https://issuetracker.google.com/issues/74428304#comment5) with Gradle plugin and was fixed in a recent alpha-version (3.3.0-alpha01). 

Until we migrate to the recent Android Gradle plugin, is there a version of FCS that works with older Gradle plugins, say 3.0.*? or, is there a version of FCS that doesn't need to have `module-info.class`?

**Comment by dangiankit** [comment]
Yes, this is not a problem with FastClasspathScanner, in particular, but with other tools. However, another project was [able to circumvent it](https://github.com/JodaOrg/joda-convert/issues/24#issuecomment-372609882), is there a similar workaround for FCS?

**Comment by lukehutch** [comment]
I had to work around this myself in a project. Sometimes you can manually override Maven dependencies. For example, `maven-compiler-plugin` version 3.7.0 depends upon an old version of ASM that does not support `module-info.class`. The solution is to manually upgrade the dependency on ASM in the Maven dependency for `maven-compiler-plugin`:

https://stackoverflow.com/a/49398936/3950982

You can probably do the same thing with the Joda or ASM dependency in your project.

I'll close this, since unfortunately this is a universal problem in the Java world right now, and it's not limited to FastClasspathScanner. We're in a transitional time, as all classpath scanner and bytecode parsing libraries and their dependencies get updated to work in the modular world. You're stuck either using all older libraries or all newer libraries, if any of the libraries or their dependencies are trying to scan classfiles directly.

**Comment by lukehutch** [comment]
Version 4.6.11 puts the `module-info.class` at `META-INF/versions/9`, which may solve this problem for some older libraries. Can you please test and let me know if it fixes the problem for you? Thank you.
